[opener]
edit = [
  { run = 'hx "$@"', block = true, desc = "Helix" },
]
zed_custom = [
    { run = 'zeditor "$@"', block = false, desc = "Zed Editor" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
]

[plugin]
append_previewers = [
    { url = "*", run = "file-extra-metadata" }
]
append_spotters = [
    { url = "*", run = "file-extra-metadata" }
]

[mgr]
linemode = "size" # Options: "none", "size", "mtime", "btime", "permissions", "owner"
